apiVersion: v1
kind: Pod
metadata:
  name: "print-envars-greeting"
  labels:
    app: "print-envars-greeting"
spec:
  containers:
  - name: print-env-container
    image: "bash:latest"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    command: ["/bin/sh", "-c", 'echo "$(GREETING) $(COMPANY) $(GROUP)"']
    env:
    - name: GREETING
      value: "Welcome to"
    - name: COMPANY
      value: "Nautilus"
    - name: GROUP
      value: "Industries"
