apiVersion: v1
kind: Pod
metadata:
  name: "envars"
  namespace: default
  labels:
    app: "envars"
spec:
  containers:
  - name: fieldref-container
    image: "redis:latest"
    command: ["/bin/sh","-c"]
    args:
      - while true;do
          echo -en '/n';
          printenv NODE_NAME POD_NAME '/n';
          printenv POD_IP POD_SERVICE_ACCOUNT '/n';
          sleep 10;
        done;
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName

    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: POD_SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          fieldPath: spec.serviceAccountName
  restartPolicy: Never
