apiVersion: v1
kind: Service
metadata:
  name: tomcat-service-datacenter
  namespace: missing!!
spec:
  type: NodePort
  selector:
    app: tomcat-service-datacenter
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 32227

---
  apiVersion: v1
  kind: "Namespace"
  metadata: 
    name: tomcat-namespace-datacenter
    labels: 
      name: tomcat-namespace-datacenter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  tomcat-deployment-datacenter
  namespace: tomcat-namespace-datacenter
  labels:
    app:  tomcat-deployment-datacenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-deployment-datacenter
  template:
    metadata:
      labels:
        app:  tomcat-deployment-datacenter
    spec:
      containers:
        - name:  tomcat-container-datacenter
          image:  gcr.io/kodekloud/centos-ssh-enabled:tomcat
          ports:
          - containerPort:  8080
            name:  tomcat
---
