apiVersion: v1
kind: Namespace
metadata:
  name: httpd-namespace-devops
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpd-service-devops
  name: httpd-service-devops
namespace: httpd-namespace-devops
spec:
  ports:
  - name: 80-80
    nodePort: 30004
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: httpd-service-devops
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: httpd_app_devops
  name: httpd-deployment-devops
  namespace: httpd-namespace-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd_app_devops
  strategy: {}
  template:
    metadata:
      labels:
        app: httpd_app_devops
    spec:
      containers:
      - image: httpd:latest
        name: httpd
        ports:
        - containerPort: 80
