# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagios-deployment
  namespace: default
  labels:
    app: nagios-deployment
spec:
  selector:
    matchLabels:
      app: nagios-deployment
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nagios-deployment
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: nagios-container
        image: jasonrivers/nagios
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
          name: "nagios"
---
kind: Service
apiVersion: v1
metadata:
  name:  nagios-service
spec:
  selector:
    app:  nagios-deployment
  type:  NodePort
  ports:
  - name:  "nagios"
    port:  80
    targetPort:  80
    nodePort: 30008