--- 
- 
  become: true
  hosts: "stapp01, stapp02, stapp03"
  name: "Create text files and create soft link"
  tasks: 
    - 
      file: 
        group: tony
        owner: tony
        path: /opt/finance/blog.txt
        state: touch
      name: "Create the blog.txt on stapp01"
      when: "inventory_hostname == \"stapp01\""
    - 
      file: 
        group: steve
        owner: steve
        path: /opt/finance/story.txt
        state: touch
      name: "Create the story.txt on stapp02"
      when: "inventory_hostname == \"stapp02\""
    - 
      file: 
        group: banner
        owner: banner
        path: /opt/finance/media.txt
        state: touch
      name: "Create the media.txt on stapp03"
      when: "inventory_hostname == \"stapp03\""
    - 
      file: 
        dest: /var/www/html
        src: /opt/finance/
        state: link
      name: "Link /opt/itadmin directory"
