---
kind: Service
apiVersion: v1
metadata:
  name: myapp
spec:
  type: NodePort
  ports:
   - port: 80
     targetPort: 80
     nodePort: 30008
  selector:
    app:  myapp
    type: front-end
---
apiVersion: v1
kind: Pod
metadata:
  name: "myapp"
  labels:
    app:  myapp
    type: front-end
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name:  back-end
spec:
  type:  ClusterIP 
  ports:
  - port:  80
    targetPort:  80
  selector:
    app:  myapp-pod-use-clusterip
    type: back-end
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-use-clusterip
  labels:
    app:  myapp-pod-use-clusterip
    type: back-end
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
  restartPolicy: Always