apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-06-14T18:50:38Z"
  name: myapp
  namespace: kube-public
  resourceVersion: "40404"
  uid: 90d2c4ad-9d3c-41b3-b689-e8e3df2e460a
spec:
  clusterIP: 10.109.0.187
  clusterIPs:
  - 10.109.0.187
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: nginx
    nodePort: 30008
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp
    type: front-end
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer:
    ingress:
    - hostname: localhost
