apiVersion: v1
kind: Pod
metadata:
  name: "ubuntu-sleeper"
  namespace: default
  labels:
    app: "MYAPP"
spec:
  containers:
  - name: ubuntu-sleeper
    image: "onetimemail/ubuntu-sleeper:latest"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    command: ["sleep"]
    args: ["10"]
