---
- name:
  hosts: all
  become: true
  gather_facts: true
  tasks: 
  - name: install httpd
    yum:
      name:  httpd
      state: latest
  - name: start httpd 
    service:
      name:  httpd
      state: started 

  - name: create contnet
    copy:
      dest: "/var/www/html/index.html"
      content: |
        This is a Nautilus sample file, created using Ansible!
  
  - name: add line contnet
    lineinfile:
      path: /var/www/html/index.html 
      insertafter: BOF 
      line: Welcome to xFusionCorp Industries!
      state: present
  - name: Creating an empty file
    file:
      path: "/var/www/html/index.html"
      state: file
      mode: '0777'
      owner: apache