# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: "pod-httpd"
  namespace: default
  labels:
    app: "httpd_app"
spec:
  containers:
  - name: httpd-container
    image: "httpd:latest"
