---
- name: Update web servers
  hosts: all
  remote_user: "{{ ansible_user }}"

  tasks:
  - name: "create /home/appdata.txt with ansible user as owner"
    file:
      path: /home/appdata.txt
      state: touch
      mode: 0644
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"